### PR TITLE
cmake: Fixed arrow include directory usage

### PR DESCRIPTION
**Pull request by TomAugspurger**
In https://github.com/mapd/mapd-core/blob/e745367c41c8dfa28487870816cf27a57a46204d/cmake/Modules/FindArrow.cmake#L62 we set `Arrow_INCLUDE_DIRS`, but the main `CMakeLists.txt` was using `Arrow_INCLUDE_DIR`, singular. Hopefully this is the right fix (I haven't used cmake before).

Before this, I could `cmake -DCMAKE_BUILD_TYPE=debug -DENABLE_CUDA=off -DENABLE_ARROW_CONVERTER=on -DArrow_LIBRARY=~/miniconda3/envs/mapd-dev/lib/libarrow.dylib ..` fine, but my `make` failed with

```
/Users/taugspurger/sandbox/mapd-core/QueryEngine/ResultSet.h:34:10: fatal error: 'arrow/table.h' file not found
#include "arrow/table.h"
 ```

I don't think this closes https://github.com/mapd/mapd-core/issues/25, as now my `make` fails with

```
[ 82%] Building CXX object QueryEngine/CMakeFiles/QueryEngine.dir/HashJoinRuntime.cpp.o
/Users/taugspurger/sandbox/mapd-core/QueryEngine/ResultSetConversion.cpp:359:22: error: no member named 'Open' in 'arrow::ipc::RecordBatchReader'
  ipc::StreamReader::Open(buf_reader, &reader);
  ~~~~~~~~~~~~~~~~~~~^
1 error generated.
make[2]: *** [QueryEngine/CMakeFiles/QueryEngine.dir/ResultSetConversion.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [QueryEngine/CMakeFiles/QueryEngine.dir/all] Error 2
make: *** [all] Error 2
```

I'm debugging that now.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
I was able fix

```
[ 82%] Building CXX object QueryEngine/CMakeFiles/QueryEngine.dir/HashJoinRuntime.cpp.o
/Users/taugspurger/sandbox/mapd-core/QueryEngine/ResultSetConversion.cpp:359:22: error: no member named 'Open' in 'arrow::ipc::RecordBatchReader'
```

by installing arrow 0.3 from source. Previously I had them installed through conda-forge. I had

```
    arrow-cpp: 0.3.0.post-np112py36_1 conda-forge
    pyarrow:   0.3.0.post-np112py36_1 conda-forge

```

in my environment, but perhaps I had something else misconfigured.

**Comment by andrewseidl** [comment]
Thanks!

And yes, it currently depends on Arrow 0.3, but I believe @m1mc has been working on bringing it up to 0.4.1.
